addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - libcups2-dev # for aeroo
      # FE
      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2

language: python
sudo: false
cache: pip

python:
  - '2.7'

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  - TRANSIFEX_ORGANIZATION='adhoc'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: Kys/o1svHJON9p6Vwv4qVSAvR/e6KGp4qKeDjWNcVeQoCfs0O35aiouLWUUiuj+JSrACL6ngha3QbeuajhYr6cYPur4NjIbCq7ePcmbEu45OcJz3l/7EiUFit8XwlRmT1uGtgknsvbn37vlF0IC28gK/1D/06CLJnxAXBOjkEd7sNmAQNAYVHQREsQsK1Pw39APAzUAtB5K5fNU3MUhQ0dCWWZ+nQeghbVM0kzf1k1iJkRDf3WDWZRRDCQdS93bMkXsw0ojkW1X5sSAqfxu89uDSyMNgMVmPsLsavatFrlUMEMZXkSlevGvNUSgoClLQMeIzbivhDME9Nv6hKcqYU8TKIYF7URtSdWwOA1FxXnrOqUjkAqvajS2P2byLYHMoRC31SH5Mh3s2A04qh+sLEf406fB8e8//7leN4l9YL2S3F6m++ZUHgN7YHXD0jhspiuC9FtnMDULUIDXGM4vaMpkZY5lhROOPXecE9FAIl9rc8s3BqlV2GMP4rrBxqo8l5SoSt4I5TOacI3niHBUHU47jhRK8NsGI/Z9ybElNeVmBI9QzZXHhciB31IPC/nRL9MgBFN1/JsHH2FXUv9OnOi8VxU5AqsCCeCG+dSFGeKZfRPZiqIHZNavL7DLitrYmN3JsizKTPGsA1CQ1788Q8oTx8C+Fn4zk+hQ+vCI+DKo=

  matrix:
  # TODO enable lint check
  #- LINT_CHECK="1"
  - TRANSIFEX="1"
  # TODO este test no funciona ya que pre-instala l10n_ar_account y al querer
  # hacerle init da error por actualizar periodo con movimientos
  # - TESTS="1" ODOO_REPO="odoo/odoo"
  - UNIT_TEST="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports -b ${VERSION}
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # odoo addons adhoc
  - git clone https://github.com/ingadhoc/odoo-addons.git ${HOME}/odoo-addons  -b ${VERSION}

  # oca account-financial-tools
  - git clone https://github.com/OCA/account-financial-tools.git ${HOME}/account-financial-tools  -b ${VERSION}

  # repository requirements
  - pip install -r requirements.txt
  - pip install -r requirements2.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
